name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (Release)
        run: dotnet publish -c Release -o build

      # Для проектных страниц GH Pages требуется base href вида /<repo-name>/
      - name: Set base href for GitHub Pages
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          BASE_PATH="/${REPO_NAME}/"
          sed -i "s|<base href=\"/\" />|<base href=\"${BASE_PATH}\" />|" build/wwwroot/index.html

      - name: Add SPA fallback (404.html)
        run: cp build/wwwroot/index.html build/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -o build

      - name: Set base href for GitHub Pages
        run: sed -i 's|<base href=\"/\" />|<base href=\"/SmartCodeLab/\" />|' build/wwwroot/index.html

      - name: SPA fallback (404.html)
        run: cp build/wwwroot/index.html build/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4