name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (Release)
        run: dotnet publish -c Release

      - name: Locate site directory
        id: locate
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          CANDIDATES=(
            bin/Release/*/publish/wwwroot
            bin/Release/*/wwwroot
            build/wwwroot
          )
          SITE_DIR=""
          for d in "${CANDIDATES[@]}"; do
            if [ -f "$d/index.html" ]; then
              SITE_DIR="$d"
              break
            fi
          done
          if [ -z "$SITE_DIR" ]; then
            echo "No wwwroot found. Directory tree:" >&2
            ls -R
            exit 1
          fi
          echo "site_dir=$SITE_DIR" >> "$GITHUB_OUTPUT"
          echo "Using site dir: $SITE_DIR"

      # Для проектных страниц GH Pages требуется base href вида /<repo-name>/
      - name: Set base href for GitHub Pages
        shell: bash
        run: |
          set -e
          REPO_NAME="${{ github.event.repository.name }}"
          BASE_PATH="/${REPO_NAME}/"
          SITE_DIR="${{ steps.locate.outputs.site_dir }}"
          sed -i "s|<base href=\"/\" />|<base href=\"${BASE_PATH}\" />|" "$SITE_DIR/index.html"
          cp "$SITE_DIR/index.html" "$SITE_DIR/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.locate.outputs.site_dir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4